version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Installing AWS CLI...
      - apt-get update && apt-get install -y awscli
  pre_build:
    commands:
      - echo Building the application...
      - npm run build
  build:
    commands:
      - echo Preparing deployment package...
      - tar -czvf build_artifact.tar.gz .next package.json package-lock.json
  post_build:
    commands:
      - echo Retrieving SSH key from Secrets Manager...
      - aws secretsmanager get-secret-value --secret-id codebuildsshkey --query SecretString --output text > ec2_key.pem
      - chmod 600 ec2_key.pem
      - echo Deploying to EC2...
      - chmod +x deploy.sh
      - ./deploy.sh ec2_key.pem

artifacts:
  files:
    - build_artifact.tar.gz
